const items = [
  {
    id: 1,
    tname: "அரிசி",
    sname: "බර",
    ename: "Rice",
    quantity: 10,
    price: 500,
    image: "https://example.com/rice.jpg",
  },
  {
    id: 2,
    tname: "கோதுமை மாவு",
    sname: "කුඹු පොතු",
    ename: "Wheat Flour",
    quantity: 5,
    price: 300,
    image: "https://example.com/wheat-flour.jpg",
  },
  {
    id: 3,
    tname: "அரிசி மாவு",
    sname: "බර පොතු",
    ename: "Rice Flour",
    quantity: 5,
    price: 250,
    image: "https://example.com/rice-flour.jpg",
  },
  {
    id: 4,
    tname: "தேநீர்",
    sname: "තෙල්",
    ename: "Tea",
    quantity: 250,
    price: 150,
    image: "https://example.com/tea.jpg",
  },
  {
    id: 5,
    tname: "சர்க்கரை",
    sname: "කඩුවෙල",
    ename: "Sugar",
    quantity: 1,
    price: 100,
    image: "https://example.com/sugar.jpg",
  },
  {
    id: 6,
    tname: "பெரிய வெங்காயம்",
    sname: "මැළුම් අණුරුව",
    ename: "Big onion",
    quantity: 2,
    price: 200,
    image: "https://example.com/big-onion.jpg",
  },
  {
    id: 7,
    tname: "பச்சை பருப்பு",
    sname: "මුදු පලතුරු",
    ename: "Green Gramme",
    quantity: 1,
    price: 150,
    image: "https://example.com/green-gramme.jpg",
  },
  {
    id: 8,
    tname: "சிவப்பு பருப்பு",
    sname: "රතු දුල්",
    ename: "Red Dhal",
    quantity: 3500,
    price: 400,
    image: "https://example.com/red-dhal.jpg",
  },
  {
    id: 9,
    tname: "கடலை பருப்பு",
    sname: "කඩල පලතුරු",
    ename: "Chick Pese",
    quantity: 1,
    price: 200,
    image: "https://example.com/chick-pese.jpg",
  },
  {
    id: 10,
    tname: "உருளைக்கிழங்கு",
    sname: "අලුත්ත",
    ename: "Potatoes",
    quantity: 2,
    price: 150,
    image: "https://example.com/potatoes.jpg",
  },
  {
    id: 11,
    tname: "உலர் மீன்",
    sname: "මාළු මාළු",
    ename: "Dry fish",
    quantity: "1 kg",
    price: 500,
    image: "https://example.com/dry-fish.jpg",
  },
  {
    id: 12,
    tname: "முட்டைகள்",
    sname: "බෝල් ඇටි",
    ename: "Eggs",
    quantity: 20,
    price: 120,
    image: "https://example.com/eggs.jpg",
  },
  {
    id: 13,
    tname: "உப்பு (200 கிராம்)",
    sname: "ලුණු",
    ename: "Salt",
    quantity: 1,
    price: 20,
    image: "https://example.com/salt.jpg",
  },
  {
    id: 14,
    tname: "தேங்காய் எண்ணெய்",
    sname: "පොල් තෙල්",
    ename: "Coconut oil",
    quantity: 2,
    price: 400,
    image: "https://example.com/coconut-oil.jpg",
  },
  {
    id: 15,
    tname: "சோயா (100 கிராம்)",
    sname: "මීනිස් මුදු",
    ename: "Soya",
    quantity: 4,
    price: 50,
    image: "https://example.com/soya.jpg",
  },
  {
    id: 16,
    tname: "சிவப்பு மிளகாய் தூள்",
    sname: "ලම්බෝලි පොඩි",
    ename: "Red Chilly Powder",
    quantity: 250,
    price: 80,
    image: "https://example.com/red-chilly-powder.jpg",
  },
  {
    id: 17,
    tname: "மஞ்சள்",
    sname: "කහ මුදු",
    ename: "Turmeric",
    quantity: 50,
    price: 30,
    image: "https://example.com/turmeric.jpg",
  },
  {
    id: 18,
    tname: "கறி பவுடர்",
    sname: "කරි පොඩි",
    ename: "Curry Powder",
    quantity: 250,
    price: 100,
    image: "https://example.com/curry-powder.jpg",
  },
  {
    id: 19,
    tname: "வறுத்த மிளகாய்",
    sname: "මුදු මිරිස්",
    ename: "Dry Chilly",
    quantity: 250,
    price: 70,
    image: "https://example.com/dry-chilly.jpg",
  },
  {
    id: 20,
    tname: "கொத்தமல்லி",
    sname: "කොමල්",
    ename: "Coriander",
    quantity: 250,
    price: 50,
    image: "https://example.com/coriander.jpg",
  },
  {
    id: 21,
    tname: "மிளகு",
    sname: "මිරිස්",
    ename: "Pepper",
    quantity: 50,
    price: 40,
    image: "https://example.com/pepper.jpg",
  },
  {
    id: 22,
    tname: "பூண்டு",
    sname: "ලැස්තුවා",
    ename: "Garlic",
    quantity: 500,
    price: 60,
    image: "https://example.com/garlic.jpg",
  },
  {
    id: 23,
    tname: "சாப்பு",
    sname: "සප්",
    ename: "Soap",
    quantity: 4,
    price: 80,
    image: "https://example.com/soap.jpg",
  },
  {
    id: 24,
    tname: "காப்பகம்",
    sname: "පොඩියක් පැක්",
    ename: "Disposable Pads",
    quantity: 2,
    price: 150,
    image: "https://example.com/disposable-pads.jpg",
  },
  {
    id: 25,
    tname: "பனதால் கார்டு",
    sname: "පැන්ඩොල්",
    ename: "Panadol",
    quantity: 1,
    price: 30,
    image: "https://example.com/panadol.jpg",
  },
];

export default commodities;
